name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build_and_test_cSharp:
    name: Build and test c#
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - name: Build C# code
      run: dotnet build
    - name: Run C# tests
      run: dotnet test


  build_and_test_ts:
    name: Build and test ts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DotnetTemplate.Web      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2
    - name: Install npm requirements
      run: npm install
    - name: Build typescript code
      run: npm run build
    - name: Run linter on ts code
      run: npm run lint
    - name: Run ts tests
      run: npm t

  slack-workflow-status:
    if: always()
    name: Post Workflow Status to slack
    needs:
      - build_and_test_cSharp
      - build_and_test_ts
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          channel: '#devops'
          name: 'Workflow Action'
          icon_emoji: ':poop:'
          icon_url: 'https://avatars0.githubusercontent.com/u/1701160?s=96&v=4'